version: "3.8"

services:
  compile:
    build: .
    volumes:
      - ./src:/nora/src
      - ./build:/nora/build
    command: bash -c "cd /nora/src && cmake -S . -B build && cmake --build build && cp /nora/bin/* /nora/build"
  nora:
    build: .
    command: /nora/build/nora
    volumes:
      - ./build:/nora/build
      - ./data:/nora/data
    depends_on:
      compile:
        condition: service_completed_successfully
    environment:
      - DEBUG=true

  test:
    build: .
    command: /nora/build/hello_test
    profiles: [ "test" ]
    volumes:
      - ./build:/nora/build
      - ./data:/nora/data
    depends_on:
      compile:
        condition: service_completed_successfully
    environment:
      - DEBUG=true

  benchmark:
    build: .
    command: /nora/scripts/run_benchmark.sh 
    profiles: [ "benchmark" ]
    volumes:
      - ./build:/nora/build
      - ./data:/nora/data
      - ./benchmark:/nora/benchmark
      - ./scripts:/nora/scripts
    depends_on:
      compile:
        condition: service_completed_successfully
    environment:
      - DEBUG=true
